site_name: pydantic-collection
site_description: Collections of pydantic model

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'

markdown_extensions:
  - codehilite

repo_name: koxudaxi/pydantic-collection
repo_url: https://github.com/koxudaxi/pydantic-collection

google_analytics:
    - 'UA-142130505-1'
    - 'auto'

nav:
    - pydantic-collection: 'index.md'
    - 'Contributing': 'contributing.md'